config/routes.rb
Contacal::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :foods, :only => [:new, :create]
  resources :user_friends, :only => [:new, :create]
  resources :user_foods, :only => [:create, :destroy, :update]
  put 'kcal_limit' => 'dashboard#update_kcal_limit', :as => :kcal_limit
  put 'user_weight' => 'dashboard#update_user_weight', :as => :user_weight
  get 'report' => 'dashboard#report', :as => :report
  get 'weight_report' => 'dashboard#weight_report', :as => :weight_report
  get 'autocomplete_food_name', :to => 'dashboard#autocomplete_food_name', :as => :autocomplete_food_name
  get 'users/confirm', :to => 'confirmation#index', :as => :user_confirm
  get ':year/:month/:day' => "dashboard#index", :as => :dashboard, :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }
  get 'authenticate', :to => 'dashboard#authenticate'
  root :to => "dashboard#index"       
  authenticate :user do
    devise_scope :user do
      get 'payment' => 'registrations#payment', :as => :payment   
    end
  end 
  

end

app/controllers/dashboard_controller.rb
# -*- encoding : utf-8 -*-
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def autocomplete_food_name
    extra_data = [:id, :name]

    pieces = []
    terms = []
    params[:term].split(" ").each do |term|
      pieces << "#{translate_to_remove_accents("name")} like #{translate_to_remove_accents("?")}"
      terms << "%#{term.downcase}%"
    end

    where_clause = "kind <> 'h' and "
    where_clause << pieces.join(" and ")
    
    @foods = Food.where(where_clause, *terms).limit(300).all.to_a
    if @foods.empty?
      @foods << Food.new(:name => "#{params[:term]} não encontrado.")
    else
      @foods.sort! do |a,b|
        if a.name.noaccents == params[:term].noaccents
          -1
        elsif b.name.noaccents == params[:term].noaccents
          +1
        elsif a.name[0,params[:term].length].noaccents == params[:term].noaccents and b.name[0,params[:term].length].noaccents != params[:term].noaccents
          -1
        elsif b.name[0,params[:term].length].noaccents == params[:term].noaccents and a.name[0,params[:term].length].noaccents != params[:term].noaccents
          +1
        elsif a.name[0,params[:term].length].noaccents == params[:term].noaccents and b.name[0,params[:term].length].noaccents != params[:term].noaccents   
          0
        else
          a.name.noaccents <=> b.name.noaccents
        end
      end
    end
    render :json => json_for_autocomplete(@foods, :name, extra_data)
  end

  def index
    begin
      @date = Date.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}")
    rescue
      @date = Date.today
    end
    @next_day = @date+1.day
    @previous_day = @date-1.day
  end
  
  def authenticate
    head :ok
  end
  
  def report
    data = []
    bar = ["",0,0,0]
    bar << current_user.kcal_limit  unless current_user.kcal_limit.nil?
    data << bar
    case params[:range]
    when 'year'
      @days = 365
    when 'month'
      @days = 30
    else
      @days = 7
    end
    (@days.days.ago.to_date..Date.today).each do |date|
      bar = [l(date, :format => :chart),consumed_kcal(date, "a"), consumed_kcal(date, "b"), consumed_kcal(date, "c")]
      bar << current_user.kcal_limit  unless current_user.kcal_limit.nil?
      data << bar
    end
    bar = ["",0,0,0]
    bar << current_user.kcal_limit  unless current_user.kcal_limit.nil?
    data << bar

    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Data' )
    data_table.new_column('number', 'Caloria Verde')
    data_table.new_column('number', 'Caloria Amarela')
    data_table.new_column('number', 'Caloria Vermelha')
    data_table.new_column('number', 'Limite diário de calorias') unless current_user.kcal_limit.nil?
    data_table.add_rows(data)
    chart_options = {
      :title => 'Controle de Calorias',
      :vAxis => {:title => 'Calorias'},
      :isStacked => true,
      :width => 900, 
      :height => 400,
      :legend => 'none',
      :colors => ['#6ba16c','#f7f143','#f75443'],
    }
    chart_options[:series] = {3 => {:type => 'line', :color => 'black', :lineWidth => 3, :visibleInLegend => false}} unless current_user.kcal_limit.nil?
    @graph = GoogleVisualr::Interactive::ColumnChart.new(data_table, chart_options)
  end

  def weight_report
    data = []
    case params[:range]
    when 'year'
      @days = 365
    else
      @days = 30
    end
    peso_antes = 0
    (@days.days.ago.to_date..Date.today).each do |date|        
      if !current_user.user_weight.find_by_date(date).nil? and current_user.user_weight.find_by_date(date).weight > peso_antes 
        peso_antes = current_user.user_weight.find_by_date(date).weight
      end
    end
    (@days.days.ago.to_date..Date.today).each do |date|        
      peso = peso_antes
      peso = current_user.user_weight.find_by_date(date).weight unless current_user.user_weight.find_by_date(date).nil?
      bar = [l(date, :format => :chart),peso]
      data << bar
      peso_antes = peso
    end

    data_table = GoogleVisualr::DataTable.new
    data_table.new_column('string', 'Data' )
    data_table.new_column('number', 'Peso')
    data_table.add_rows(data)
    chart_options = {
      :title => 'Controle de peso',
      :vAxis => {:title => 'Peso'},
      :isStacked => true,
      :width => 900, 
      :height => 400, 
      :lineWidth => 3,
      :legend => 'none',
      :colors => ['#f75443'],
    }
    @graph = GoogleVisualr::Interactive::LineChart.new(data_table, chart_options)
  end

  def update_kcal_limit
    current_user.update_attributes({:kcal_limit => params[:kcal_limit]})
  end
  
  def update_user_weight        
    if (params[:kcal_limit].to_f == 0)
      current_user.user_weight.find_or_create_by(date: params[:date].to_date).destroy
    else
      current_user.user_weight.find_or_create_by(date: params[:date].to_date).update_attributes(:weight => params[:kcal_limit].gsub(",",".").to_f, :date => params[:date].to_date)
    end  
  end
  
  private
  def consumed_kcal(date, kind)
    current_user.consumed_kcal(:date => date, :kind => kind)
  end

  def translate_to_remove_accents(value)
    %{translate(lower(#{value}),'áâãäåāăąèééêëēĕėęěìíîïìĩīĭóôõöōŏőùúûüũūŭůçćčĉċ','aaaaaaaaeeeeeeeeeeiiiiiiiiooooooouuuuuuuccccc')}
  end

end

app/helpers/dashboard_helper.rb
# -*- encoding : utf-8 -*-
module DashboardHelper
  def display_daily_total(date)
    spent    = user.spent_kcal(:date => date)
    consumed = user.consumed_kcal(:date => date)
    net = consumed - spent

    if spent > 0
      "#{number_with_precision(consumed, :precision => 0)} ingeridas - #{number_with_precision(spent, :precision => 0)} gastas = #{number_with_precision(net, :precision => 0)}"
    else
      number_with_precision(consumed, :precision => 0)
    end
  end
end

app/views/dashboard/_program_result.html.erb
<% if total_kcal == 0 %>
  <% if current_user.sign_in_count <= 1 %>  
  <%- current_user.update_attribute(:sign_in_count, 2) -%> 
  <div class="notice">Seja bem vindo, <strong><%= current_user.name %></strong>! Se tiver dúvidas sobre como usar o sistema, confira a nossa <%= link_to "ajuda", '/ajuda.html', :class => "terms-of-use-fancybox", :id => "primeira_vez", :data => {:fancybox => true, :type => 'iframe'} %>.</div>
  <% else %>
    <div class="notice">Bem vindo de volta, <strong><%= current_user.name %></strong>! Confira nossas últimas novidades em <%= link_to "nosso blog", 'http://www.contacal.com.br/blog', :class => "terms-of-use-fancybox", :data => {:fancybox => true, :type => 'iframe'} %>.</div>
  <% end %>
<% elsif percent_kcal_kind_b <= 35 and percent_kcal_kind_c <= 10 %>
  <div class="notice">Parabéns, <strong><%= current_user.name %></strong>! Sua dieta está dentro dos <%= link_to 'padrões recomendados', 'http://www.contacal.com.br/o-que-sao-as-calorias-vermelhas-amarelas-e-verdes/', :class => "terms-of-use-fancybox", :data => {:fancybox => true, :type => 'iframe'} %>.</div>
<% else %>
  <div class="alert">Quase lá, <strong><%= current_user.name %></strong>! Continue atualizando sua dieta com <%= link_to 'mais alimentos verdes e menos alimentos vermelhos', 'http://www.contacal.com.br/o-que-sao-as-calorias-vermelhas-amarelas-e-verdes/', :class => "terms-of-use-fancybox", :data => {:fancybox => true, :type => 'iframe'} %>.</div>
<% end %>

app/views/dashboard/index.html.erb
<% content_for :header_info do %>
<!--  <div id="kcal-limit">
    <%= link_to "Limite diário de calorias", "http://www.contacal.com.br/qual-o-limite-de-calorias-indicado/", :target => '_blank' %>:
    <br />
    <% if current_user.kcal_limit.nil? %>
      <span id="kcal-limit-value"><%= link_to "0 Kcal", '#', :id => 'kcal-limit-link' %></span>
      <span id="change-kcal-label">definir</span>
    <% else %>
      <span id="kcal-limit-value"><%= link_to "#{current_user.kcal_limit} Kcal", '#', :id => 'kcal-limit-link' %></span>
      <span id="change-kcal-label">alterar</span>
    <% end -%>
    
    <%= form_tag(kcal_limit_path, :remote => true, :method => :put, :id => 'kcal-limit-form', :style => 'display: none') do |f| %>
      <%= text_field_tag :kcal_limit, current_user.kcal_limit %>
      <%= submit_tag "Atualizar" %> 
    <% end -%>
  </div>-->
<div id="kcal-limit">
  <% peso = current_user.user_weight.find_by_date(l(@date).to_date) %>  
  <%- if (Date.today == l(@date).to_date) -%>
  Seu <%= link_to "peso", weight_report_url %> atual:  
  <%- else -%>
  Seu  <%= link_to "peso", weight_report_url %> em <%= l(@date) %>:
  <%- end -%>
  <br/>
  <% if current_user.user_weight.find_by_date(l(@date).to_date).nil? %>
    <span id="kcal-limit-value"><%= link_to "não informado", '#', :id => 'kcal-limit-link' %></span>
  <% else %>
    <span id="kcal-limit-value"><%= link_to "#{peso.weight} Kg", '#', :id => 'kcal-limit-link' %></span>
  <% end -%>
  <span id="change-kcal-label">alterar</span>
  <%= form_tag(user_weight_path, :remote => true, :method => :put, :id => 'kcal-limit-form', :style => 'display: none') do |f| %>
  <%= hidden_field_tag :date, l(@date).to_date %>
  <% if current_user.user_weight.find_by_date(l(@date).to_date).nil? %>
    <%= hidden_field_tag :user_foods_id, 0 %>
    <%= text_field_tag :kcal_limit, 0 %>
  <% else %>
    <%= hidden_field_tag :user_foods_id, peso.id %>
    <%= text_field_tag :kcal_limit, peso.weight %>
  <% end -%>
    <%= submit_tag "Atualizar" %> 
  <% end -%>
</div> 
<% end %>







<%= javascript_tag %{
$(function() {
  $('#kcal-limit-link').click(function() {
    $('#kcal-limit-value').hide();
    $('#change-kcal-label').hide();
    $('#kcal-limit-form').show();
    $('#kcal_limit').focus();
    $('#kcal_limit').select();
    return false;
  });
});
} %>





<div id="kcal-measure">
  <div class="title">Total: <strong><span id="total-kcal"><%= display_daily_total(current_date) %></span></strong> 
		<%- if current_user.kcal_limit != nil and current_user.kcal_limit > 0 -%>
          de <strong><a href="/users/edit"><%= current_user.kcal_limit %></a></strong> Kcal diários 
	    <%- else -%>
	      Kcal (<%= link_to "Definir limite diário de calorias", edit_user_registration_url %>)
	    <%- end -%>
	    
	</div>
  <div id="progress">
    <%= render :partial => "progress" %>
  </div>
</div>


<%= link_to "Relatório", report_url, :id => "report" %>

<!--div id="weight-info">
  <div class="title">Seu peso:</div>
  <div id="weight">89kg</div>
</div-->

<nav>
  <div id="prev-date"><%= link_to 'anterior', dashboard_path(:year => @previous_day.year, :month => "%02d" % @previous_day.month, :day => "%02d" % @previous_day.day) %></div>
  <% if l(@date) != l(Date.today) %>
    <div id="current-date" class="not-today"><%= link_to "Voltar para hoje", root_url %> <a href="#" id="toggle-calendar"><%= l(@date) %></a></div>
  <% else %>
    <div id="current-date"><a href="#" id="toggle-calendar"><%= l(@date) %></a></div>
  <% end %>
  <div id="next-date"><%= link_to 'próximo', dashboard_path(:year => @next_day.year, :month => "%02d" % @next_day.month, :day => "%02d" % @next_day.day) %></div>
<!--  <% if l(@date) != l(Date.today) %>
    <div id="next-date"><%= link_to 'próximo', dashboard_path(:year => @next_day.year, :month => "%02d" % @next_day.month, :day => "%02d" % @next_day.day) %></div>
  <% end %>-->
</nav>

<div id="calendar"></div>

<div id="program-result">
  <%= render 'program_result' %>
</div>

<%= form_tag do -%>
  <%- [:breakfast, :brunch, :lunch, :tea, :dinner, :supper].each do |meal| -%>
    <div class="meal-box">
      <h2><span class="total-kcal"><span id="total-kcal-<%= meal %>"><%= number_with_precision(current_user.consumed_kcal(:date => @date, :meal => meal), :precision => 0) %></span> Kcal</span><%=t ".#{meal}" %></h2>
      <%= autocomplete_field :food_name, '', autocomplete_food_name_path, :class => "food_name_autocomplete", :"data-meal" => meal, :placeholder => "Adicione um alimento" -%>
      <div class="meals">
        <ul id="foods-<%= meal %>">
          <%= render current_user.foods_and_exercises(:date => @date, :meal => meal), :as => 'user_food' %>
        </ul>
      </div>
    </div>
  <%- end -%>
  
  <div style="clear: both; margin-bottom: 20px"></div>
<%- end -%>

<%= javascript_tag %{
$(function() {
  $('.food_name_autocomplete').autocomplete({
    source: '/autocomplete_food_name',
    minLength: 2,
    select: function( event, ui ) {
      $.ajax({
        type: 'POST',
        url: "#{user_foods_url}",
        dataType: "script",
        data: {
          user_food: {
            date: '#{@date.to_s(:db)}',
            food_id: ui.item.id,
            meal: $(this).attr('data-meal')
          }
        }
      });
      $(this).val('');
      return false;
    }
  });
  
  $('#calendar').datepicker({
    inline: true,
    dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    dayNamesMin: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
//    maxDate: #{l(Date.today)},
    prevText: "Anterior",
    nextText: "Próximo",
    onSelect: function(dateText, inst) {
      new_date = dateText.split("/")
      location.href = "/" + new_date[2] + "/" + new_date[0] + "/" + new_date[1]
    }
  });
});
} %>

app/views/dashboard/index.mobile.erb
<% content_for :header_info do %>
<!--  <div id="kcal-limit">
    <%= link_to "Limite diário de calorias", "http://www.contacal.com.br/qual-o-limite-de-calorias-indicado/", :target => '_blank' %>:
    <br />
    <% if current_user.kcal_limit.nil? %>
      <span id="kcal-limit-value"><%= link_to "0 Kcal", '#', :id => 'kcal-limit-link' %></span>
      <span id="change-kcal-label">definir</span>
    <% else %>
      <span id="kcal-limit-value"><%= link_to "#{current_user.kcal_limit} Kcal", '#', :id => 'kcal-limit-link' %></span>
      <span id="change-kcal-label">alterar</span>
    <% end -%>
    
    <%= form_tag(kcal_limit_path, :remote => true, :method => :put, :id => 'kcal-limit-form', :style => 'display: none') do |f| %>
      <%= text_field_tag :kcal_limit, current_user.kcal_limit %>
      <%= submit_tag "Atualizar" %> 
    <% end -%>
  </div>-->
<!--<div id="kcal-limit">
  <% peso = current_user.user_weight.find_by_date(l(@date).to_date) %>  
  <%- if (Date.today == l(@date).to_date) -%>
  Seu <%= link_to "peso", weight_report_url %> atual:  
  <%- else -%>
  Seu  <%= link_to "peso", weight_report_url %> em <%= l(@date) %>:
  <%- end -%>
  <br/>
  <% if current_user.user_weight.find_by_date(l(@date).to_date).nil? %>
    <span id="kcal-limit-value"><%= link_to "não informado", '#', :id => 'kcal-limit-link' %></span>
  <% else %>
    <span id="kcal-limit-value"><%= link_to "#{peso.weight} Kg", '#', :id => 'kcal-limit-link' %></span>
  <% end -%>
  <span id="change-kcal-label">alterar</span>
  <%= form_tag(user_weight_path, :remote => true, :method => :put, :id => 'kcal-limit-form', :style => 'display: none') do |f| %>
  <%= hidden_field_tag :date, l(@date).to_date %>
  <% if current_user.user_weight.find_by_date(l(@date).to_date).nil? %>
    <%= hidden_field_tag :user_foods_id, 0 %>
    <%= text_field_tag :kcal_limit, 0 %>
  <% else %>
    <%= hidden_field_tag :user_foods_id, peso.id %>
    <%= text_field_tag :kcal_limit, peso.weight %>
  <% end -%>
    <%= submit_tag "Atualizar" %> 
  <% end -%>
</div> -->
<% end %>







<%= javascript_tag %{
$(function() {
  $('#kcal-limit-link').click(function() {
    $('#kcal-limit-value').hide();
    $('#change-kcal-label').hide();
    $('#kcal-limit-form').show();
    $('#kcal_limit').focus();
    $('#kcal_limit').select();
    return false;
  });
});
} %>





<div id="kcal-measure">
  <div class="title">Total: <strong><span id="total-kcal"><%= display_daily_total(current_date) %></span></strong> 
		<%- if current_user.kcal_limit != nil and current_user.kcal_limit > 0 -%>
          de <strong><a href="/users/edit"><%= current_user.kcal_limit %></a></strong> Kcal diários 
	    <%- else -%>
	      Kcal
	    <%- end -%>
	    
	</div>
  <div id="progress">
    <%= render :partial => "progress" %>
  </div>
</div>

<!--<%= link_to "Relatório", report_url, :id => "report" %>-->

<!--div id="weight-info">
  <div class="title">Seu peso:</div>
  <div id="weight">89kg</div>
</div-->

<nav>
  <div id="prev-date"><%= link_to 'anterior', dashboard_path(:year => @previous_day.year, :month => "%02d" % @previous_day.month, :day => "%02d" % @previous_day.day) %></div>
  <% if l(@date) != l(Date.today) %>
    <div id="current-date" class="not-today"><%= link_to "Voltar para hoje", root_url %> <a href="#" id="toggle-calendar"><%= l(@date) %></a></div>
  <% else %>
    <div id="current-date"><a href="#" id="toggle-calendar"><%= l(@date) %></a></div>
  <% end %>
  <div id="next-date"><%= link_to 'próximo', dashboard_path(:year => @next_day.year, :month => "%02d" % @next_day.month, :day => "%02d" % @next_day.day) %></div>
<!--  <% if l(@date) != l(Date.today) %>
    <div id="next-date"><%= link_to 'próximo', dashboard_path(:year => @next_day.year, :month => "%02d" % @next_day.month, :day => "%02d" % @next_day.day) %></div>
  <% end %>-->
</nav>

<div id="calendar"></div>

<div id="program-result">
  <%= render 'program_result' %>
</div>

<%= form_tag do -%>
  <%- [:breakfast, :brunch, :lunch, :tea, :dinner, :supper].each do |meal| -%>
    <div class="meal-box" id="<%= meal %>">
      <h2><span class="total-kcal"><span id="total-kcal-<%= meal %>"><%= number_with_precision(current_user.consumed_kcal(:date => @date, :meal => meal), :precision => 0) %></span> Kcal</span><%=t ".#{meal}" %></h2>
      <%= autocomplete_field :food_name, '', autocomplete_food_name_path, :class => "food_name_autocomplete", :"data-meal" => meal, :placeholder => "Adicione um alimento" -%>
    </div>
    <div class="meals" id="meals-<%= meal %>">
      <ul id="foods-<%= meal %>" class="meals-item">
        <%= render current_user.foods_and_exercises(:date => @date, :meal => meal), :as => 'user_food' %>
      </ul>
    </div>
  <%- end -%>
  
  <div style="clear: both; margin-bottom: 20px"></div>
<%- end -%>

<%= javascript_tag %{
$(function() {  
  $('.food_name_autocomplete').autocomplete({
    source: '/autocomplete_food_name',
    minLength: 2,
    select: function( event, ui ) {
      $.ajax({
        type: 'POST',
        url: "#{user_foods_url}",
        dataType: "script",
        data: {
          user_food: {
            date: '#{@date.to_s(:db)}',
            food_id: ui.item.id,
            meal: $(this).attr('data-meal')
          }
        }
      });
      $(this).val('');
      return false;
    }
  });
  
  $('#calendar').datepicker({
    inline: true,
    dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
    dayNamesMin: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
    monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
    monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
//    maxDate: #{l(Date.today)},
    prevText: "Anterior",
    nextText: "Próximo",
    onSelect: function(dateText, inst) {
      new_date = dateText.split("/")
      location.href = "/" + new_date[2] + "/" + new_date[0] + "/" + new_date[1]
    }
  });
});

}
%>

app/views/dashboard/report.html.erb
<h1 id="report-title">
<% if @days == 30 %>
       <span style="float: right">
	      <%= link_to '7 dias'.html_safe, report_path %> | <%= link_to 'ano'.html_safe, report_path(:range => 'year') %>
       </span>
       Relatório de controle de calorias ingeridas nos últimos 30 dias
<% elsif @days == 365 %>
    <span style="float: right">
      <%= link_to '7 dias'.html_safe, report_path %> | <%= link_to '30 dias'.html_safe, report_path(:range => 'month') %>
    </span>
    Relatório de controle de calorias ingeridas no último ano
<% else %>
      <span style="float: right">
        <%= link_to '30 dias'.html_safe, report_path(:range => 'month') %> | <%= link_to 'ano'.html_safe, report_path(:range => 'year') %>
      </span>
      Relatório de controle de calorias ingeridas nos últimos 7 dias
<% end -%>
</h1>

<div id="graph">&nbsp;</div>
<script src='https://www.google.com/jsapi'></script>
<%= raw @graph.to_js("graph") %>

<p>
  <%= link_to "&laquo; voltar para o programa".html_safe, root_path %>
<span style="float: right">
  <%= link_to "ver relatório de peso  &raquo;".html_safe, weight_report_path %>
</span>
</p>

app/views/dashboard/report.mobile.erb
<h1 id="report-title">
    <% if @days == 30 %>
      <span style="float: right">
	      <%= link_to '7 dias'.html_safe, report_path %> | <%= link_to 'ano'.html_safe, report_path(:range => 'year') %>
      </span>
      Relatório de controle de calorias ingeridas nos últimos 30 dias
    <% elsif @days == 365 %>
    <span style="float: right">
      <%= link_to '7 dias'.html_safe, report_path %> | <%= link_to '30 dias'.html_safe, report_path(:range => 'month') %>
    </span>
    Relatório de controle de calorias ingeridas no último ano
    <% else %>
      <span style="float: right">
        <%= link_to '30 dias'.html_safe, report_path(:range => 'month') %> | <%= link_to 'ano'.html_safe, report_path(:range => 'year') %>
      </span>
      Relatório de controle de calorias ingeridas nos últimos 7 dias
    <% end -%>
</h1>

<div id="graph">&nbsp;</div>
<script src='https://www.google.com/jsapi'></script>
<%= raw @graph.to_js("graph") %>

<p>
  <%= link_to "&laquo; voltar para o programa".html_safe, root_path %>
<span style="float: right">
  <%= link_to "ver relatório de peso  &raquo;".html_safe, weight_report_path %>
</span>
</p>

app/views/dashboard/update_kcal_limit.js.erb
$('#kcal-limit-value a').html('<%= current_user.kcal_limit.to_i.to_s %>');
$('#kcal_limit').val('<%= current_user.kcal_limit.to_s%>');
$('#kcal-limit-value a').append(" Kcal");
$('#kcal-limit-form').hide();
$('#kcal-limit-value').show();

app/views/dashboard/weight_report.html.erb
<h1 id="report-title">
    <% if @days == 365 %>
      <span style="float: right">
        <%= link_to 'Ver últimos 30 dias &raquo;'.html_safe, weight_report_path %>
      </span>
      Relatório de controle de peso no último ano
    <% else %>
      <span style="float: right">
        <%= link_to 'Ver evolução no ano &raquo;'.html_safe, weight_report_path(:range => 'year') %>
      </span>
      Relatório de controle de peso nos últimos 30 dias
    <% end -%>
</h1>

<div id="graph">&nbsp;</div>
<script src='https://www.google.com/jsapi'></script>
<%= raw @graph.to_js("graph") %>

<p>
  <%= link_to "&laquo; voltar para o programa".html_safe, root_path %>
<span style="float: right">
  <%= link_to "ver relatório de calorias ingeridas &raquo;".html_safe, report_path %>
</span>
</p>

app/views/dashboard/weight_report.mobile.erb
<h1 id="report-title">
    <% if @days == 365 %>
      <span style="float: right">
        <%= link_to 'Ver últimos 30 dias &raquo;'.html_safe, weight_report_path %>
      </span>
      Relatório de controle de peso no último ano
    <% else %>
      <span style="float: right">
        <%= link_to 'Ver evolução no ano &raquo;'.html_safe, weight_report_path(:range => 'year') %>
      </span>
      Relatório de controle de peso nos últimos 30 dias
    <% end -%>
</h1>

<div id="graph">&nbsp;</div>
<script src='https://www.google.com/jsapi'></script>
<%= raw @graph.to_js("graph") %>

<p>
  <%= link_to "&laquo; voltar para o programa".html_safe, root_path %>
<span style="float: right">
  <%= link_to "ver relatório de calorias ingeridas &raquo;".html_safe, report_path %>
</span>
</p>