config/routes.rb
Contacal::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :foods, :only => [:new, :create]
  resources :user_friends, :only => [:new, :create]
  resources :user_foods, :only => [:create, :destroy, :update]
  put 'kcal_limit' => 'dashboard#update_kcal_limit', :as => :kcal_limit
  put 'user_weight' => 'dashboard#update_user_weight', :as => :user_weight
  get 'report' => 'dashboard#report', :as => :report
  get 'weight_report' => 'dashboard#weight_report', :as => :weight_report
  get 'autocomplete_food_name', :to => 'dashboard#autocomplete_food_name', :as => :autocomplete_food_name
  get 'users/confirm', :to => 'confirmation#index', :as => :user_confirm
  get ':year/:month/:day' => "dashboard#index", :as => :dashboard, :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }
  get 'authenticate', :to => 'dashboard#authenticate'
  root :to => "dashboard#index"       
  authenticate :user do
    devise_scope :user do
      get 'payment' => 'registrations#payment', :as => :payment   
    end
  end 
  

end

app/models/user_food.rb
class UserFood < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates :user, :food, :date, :presence => true
  validates :amount, :numericality => true
  validates :meal, :inclusion => %w( breakfast brunch lunch tea dinner supper )
  before_save :set_kcal

  protected
  
  def set_kcal
    return if amount.nil? or food.nil? or food.kcal.nil?
    self.kcal = amount*food.kcal
  end
end

app/controllers/user_foods_controller.rb
# -*- encoding : utf-8 -*-
class UserFoodsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user_food = current_user.user_foods.create(user_food_params.merge(:amount => 1))
  end

  def update
    @user_food = current_user.user_foods.find(params[:id])
    @user_food.update_attributes(user_food_params)
  end

  def destroy
    @user_food = current_user.user_foods.find(params[:id])
    @user_food.destroy
  end     
  
  private 
  
  def user_food_params 
    params.require(:user_food).permit(:food, :food_id, :amount, :meal, :date)
  end 
end

app/views/user_foods/_update_meal.js.erb
$('#total-kcal').html('<%= display_daily_total(@user_food.date) %>');
$('#total-kcal-<%= @user_food.meal %>').html('<%= number_with_precision(current_user.consumed_kcal(:meal => @user_food.meal, :date => @user_food.date), :precision => 0) %>');
$('#foods-<%= @user_food.meal %>').html('<%= escape_javascript(render current_user.foods_and_exercises(:meal => @user_food.meal, :date => @user_food.date), :as => 'user_food') %>');
$('#progress').html('<%= escape_javascript(render :partial => "dashboard/progress") %>');
$('#program-result').html('<%= escape_javascript(render :partial => "dashboard/program_result") %>');


$(".meals ul li").mouseover(function() {
  $(this).addClass("hover");
  $(this).children("a.remove").show();
}).mouseout(function() {
  $(this).removeClass("hover");
  $(this).children("a.remove").hide();
});

app/views/user_foods/_update_meal.mobile.js.erb
$('#total-kcal').html('<%= display_daily_total(@user_food.date) %>');
$('#total-kcal-<%= @user_food.meal %>').html('<%= number_with_precision(current_user.consumed_kcal(:meal => @user_food.meal, :date => @user_food.date), :precision => 0) %>');
$('#foods-<%= @user_food.meal %>').html('<%= escape_javascript(render current_user.foods_and_exercises(:meal => @user_food.meal, :date => @user_food.date), :as => 'user_food') %>');
$('#progress').html('<%= escape_javascript(render :partial => "dashboard/progress") %>');
$('#program-result').html('<%= escape_javascript(render :partial => "dashboard/program_result") %>');

app/views/user_foods/_user_food.html.erb
<% slider_id = "slider-meal-#{user_food.id}" %>

<% step = 0.5 %>
<% step = 0.1 if user.small_portions %>
<li>                                     
  <%= "#{user_food.food.name}<br />#{user_food.food.weight} (#{user_food.food.measure})<br /><em><span id='slider-meal-amount-#{user_food.id}'>#{number_with_precision(user_food.amount, :strip_insignificant_zeros => true)}</span> x #{user_food.food.kcal} Kcal</em> = <strong><span id='slider-meal-total-#{user_food.id}'>#{number_with_precision(user_food.kcal, :strip_insignificant_zeros => true)}</span> Kcal</strong> #{image_tag("#{user_food.food.kind}.png")}".html_safe %>
  <%= link_to "Remover", user_food_url(user_food.id, :format => :js), :method => :delete, :remote => true, :class => "remove removeMob" %>
   <div class="slide">
      <div class="sliderBt down-slider" id='down-<%= slider_id %>'><a href="javascript:void(0)">-</a></div> 
	  <div class="sliderBt up-slider" id='up-<%= slider_id %>'><a href="javascript:void(0)">+</a></div>
      <div class="slider" id="<%= slider_id %>">&nbsp;</div>       
    </div>
<!--    <div class="slider-none" id="<%= slider_id %>">&nbsp;</div> -->
</li>
<%= javascript_tag %{
$(function() {
  var s = $( "##{slider_id}" ).slider({
    value: #{user_food.amount},
    min: #{step},
    max: 10,
    step: #{step},
    slide: function( event, ui ) {
      $('#slider-meal-amount-#{user_food.id}').html(ui.value.toFixed(1).toString().replace('.',','));
      $('#slider-meal-total-#{user_food.id}').html((ui.value.toFixed(1)*#{user_food.food.kcal}).toString().replace('.',','));
    },
    change: function( event, ui ) {
      $.ajax({
        type: 'PUT',
        url: "#{user_food_url(user_food)}",
        dataType: "script",
        data: {
          user_food: {
            amount: ui.value
          }
        }
      });
    }
  });
  $('#down-#{slider_id}').click(function() {
    s.slider('value', s.slider('value') - s.slider( "option", "step" ) );   
  });
  $('#up-#{slider_id}').click(function() {
    s.slider('value', s.slider('value') + s.slider( "option", "step" ) );   
  });
});
} %>

app/views/user_foods/_user_food.mobile.erb
<% slider_id = "slider-meal-#{user_food.id}" %>

<% step = 0.5 %>
<% step = 0.1 if user.small_portions %>
<li>                                     
  <%= "#{user_food.food.name}<br />#{user_food.food.weight} (#{user_food.food.measure})<br /><em><span id='slider-meal-amount-#{user_food.id}'>#{number_with_precision(user_food.amount, :strip_insignificant_zeros => true)}</span> x #{user_food.food.kcal} Kcal</em> = <strong><span id='slider-meal-total-#{user_food.id}'>#{number_with_precision(user_food.kcal, :strip_insignificant_zeros => true)}</span> Kcal</strong> #{image_tag("#{user_food.food.kind}.png")}".html_safe %>
  &nbsp;&nbsp;(<%= link_to "Remover", user_food_url(user_food.id, :format => :js), :method => :delete, :remote => true %>)
  <div class="slide">
    <div class="sliderBt down-slider" id='down-<%= slider_id %>'><a href="javascript:void(0)">-</a></div> 
    <div class="sliderBt up-slider" id='up-<%= slider_id %>'><a href="javascript:void(0)">+</a></div>
    <div class="slider" id="<%= slider_id %>">&nbsp;</div>       
  </div>

</li>
<%= javascript_tag %{
$(function() {
  var s = $( "##{slider_id}" ).slider({
    value: #{user_food.amount},
    min: #{step},
    max: 10,
    step: #{step},
    slide: function( event, ui ) {
      $('#slider-meal-amount-#{user_food.id}').html(ui.value.toFixed(1).toString().replace('.',','));
      $('#slider-meal-total-#{user_food.id}').html((ui.value.toFixed(1)*#{user_food.food.kcal}).toString().replace('.',','));
    },
    change: function( event, ui ) {
      $.ajax({
        type: 'PUT',
        url: "#{user_food_url(user_food)}",
        dataType: "script",
        data: {
          user_food: {
            amount: ui.value
          }
        }
      });
    }
  });
  $('#down-#{slider_id}').click(function() {
    s.slider('value', s.slider('value') - s.slider( "option", "step" ) );   
  });
  $('#up-#{slider_id}').click(function() {
    s.slider('value', s.slider('value') + s.slider( "option", "step" ) );   
  });
});
} %>

app/views/user_foods/create.js.erb
<%= render :partial => "update_meal.mobile.js.erb" %>

app/views/user_foods/destroy.js.erb
<%= render :partial => "update_meal" %>

app/views/user_foods/update.js.erb
<%= render :partial => "update_meal" %>