config/routes.rb
Contacal::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }
  resources :foods, :only => [:new, :create]
  resources :user_friends, :only => [:new, :create]
  resources :user_foods, :only => [:create, :destroy, :update]
  put 'kcal_limit' => 'dashboard#update_kcal_limit', :as => :kcal_limit
  put 'user_weight' => 'dashboard#update_user_weight', :as => :user_weight
  get 'report' => 'dashboard#report', :as => :report
  get 'weight_report' => 'dashboard#weight_report', :as => :weight_report
  get 'autocomplete_food_name', :to => 'dashboard#autocomplete_food_name', :as => :autocomplete_food_name
  get 'users/confirm', :to => 'confirmation#index', :as => :user_confirm
  get ':year/:month/:day' => "dashboard#index", :as => :dashboard, :constraints => { :year => /\d{4}/, :month => /\d{2}/, :day => /\d{2}/ }
  get 'authenticate', :to => 'dashboard#authenticate'
  root :to => "dashboard#index"       
  authenticate :user do
    devise_scope :user do
      get 'payment' => 'registrations#payment', :as => :payment   
    end
  end 
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>ContaCal - o seu diário alimentar virtual!</title>
  <meta name="description" content="Sistema simples e eficiente para controlar suas calorias diárias. Basta vc registrar suas refeições e o sistema calcula automaticamente a quantidade de calorias ingerida e ainda informa se as calorias ingeridas são do tipo verde, amarela ou vermelha. As cores servem para indicar quão recomendável é ingerir o alimento. Se é um alimento de calorias vermelhas, é melhor evitá-lo ao máximo. Calorias amarelas podem ser ingeridas com moderação. Já as calorias verdes podem ser ingeridas sem restrição. Como sugestão, procure seguir a seguinte regra, não mais que 10% de calorias vermelhas, não mais que 35% de calorias amarelas e pelo menos 55% de calorias verdes.">
  <meta name="keywords" content="contador de calorias, conta calorias, calorias, emagrecer, emagrecimento, controle de calorias, controle de peso, perder peso, diário de calorias, perda de peso, alimentação saudável, nutrição, informação nutricional">
  <link href='/favicon.png' rel='shortcut icon'>
  <link href="/images/ContaCal-Icone-57x57.png" rel="apple-touch-icon" />
  <link href="/images/ContaCal-Icone-76x76.png" rel="apple-touch-icon" sizes="76x76" />
  <link href="/images/ContaCal-Icone-120x120.png" rel="apple-touch-icon" sizes="120x120" />
  <link href="/images/ContaCal-Icone-152x152.png" rel="apple-touch-icon" sizes="152x152" />
  <link href="/images/ContaCal-Icone-180x180.png" rel="apple-touch-icon" sizes="180x180" />
  <link href="/images/ContaCal-Icone-192x192.png" rel="icon" sizes="192x192" />
  <link href="/images/ContaCal-Icone-128x128.png" rel="icon" sizes="128x128" />
  <%= stylesheet_link_tag "contacal", "jquery-ui", "jquery.fancybox", "reset" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>

  <!--[if lt IE 9]>
    <script src='http://html5shim.googlecode.com/svn/trunk/html5.js'></script>
  <![endif]-->

  <!--[if lte IE 7]>
    <link href="/stylesheets/iefix.css" media="all" rel="stylesheet" />
  <![endif]-->

</head>
<body id="<%= controller.controller_name %>">
  <header>
    <%- if user_signed_in? -%> 
    <%- if (current_user.status == 1 or current_user.status == 10) and user.expire_at.nil? -%>   
       <%- user.update_attribute(:expire_at, Date.today-1) -%>
    <%- end -%>
      <div id="masthead">
        <p align=right>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<%- if current_user.kcal_limit.nil? or current_user.kcal_limit == 0 -%>
           <%= link_to "Definir limite diário", edit_user_registration_url %> &bull;
	    <%- end -%> 
	    <%= link_to "Renovar acesso", payment_url %> &bull; <%= link_to "Alterar Dados", edit_user_registration_url %> &bull; <%= link_to "Ajuda", '/ajuda.html', :class => "terms-of-use-fancybox", :data => {:fancybox => true, :type => 'iframe'} %> &bull; <%= link_to "Blog", 'http://contacal.com.br/blog'%> &bull; <%= link_to "Site", 'http://contacal.com.br'%> &bull; <%= link_to "Sair", destroy_user_session_url, :method => :delete %>
      </div>
    <%- end -%>
    <div id="logo"><a href="<%= root_url(:protocol => "http") %>">ContaCal</a></div>
	<%- if (current_user.status == 0 or current_user.status == 1 or current_user.status == 10 or current_user.status == 2 or current_user.status == 4 or current_user.status == 20 or current_user.status == 40) and !user.expire_at.nil? and Date.today+10 > user.expire_at -%>
	<div id="subscriber">

		<%- if Date.today < user.expire_at -%>
          <br>Seu acesso expira em <strong><%= user.expire_at.strftime("%d/%m/%Y") %></strong>. <a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- elsif Date.today == user.expire_at -%>
		  <br>Seu acesso está expirando <strong>hoje</strong>!  <a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- else -%>
	      <br>Seu acesso expirou em <strong><%= user.expire_at.strftime("%d/%m/%Y") %></strong>. <a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- end -%>
    </div>
    <%- else -%>
	<div id="subscriber">
		<br>
    </div>
	<%- end -%>
    <%= yield(:header_info) %>  

 


 </header>
  <hr />
  <%- if (current_user.status == 0 or current_user.status == 1 or current_user.status == 10 or current_user.status == 2 or current_user.status == 4 or current_user.status == 20 or current_user.status == 40)  and !user.expire_at.nil? and Date.today > user.expire_at -%>
<br /><br /><br />
<div class="alert" style="position: relative; margin-left: auto; margin-right: auto; margin-top: auto; width: 350px">
<b>Seu acesso expirou... :-(</b><br /><br /><a href=<%=payment_url%>><font color=#dd0000><b>Renove já o seu acesso</b></font></a> para voltar a utilizar seu diário alimentar virtual e continuar a registrar suas refeições!<!--<br /><br />Quer usar mais alguns dias grátis? <a href="http://admin.contacal.com.br/user_friends/user_friend.cgi?from=<%=current_user.email%>" class="terms-of-use-fancybox"><font color=#dd0000><b>Indique</b></font></a> para seus amigos!-->
<br /><br />
</div>
  <%- else -%>
  <section role="main">
    <%= yield %>
  </section>
  <%- end -%>                  
  <hr />
  <footer>
    <p align=center><!--Copyright &copy; 2011 ContaCal. Dúvidas? Sugestões? <%= link_to 'Fale conosco', 'http://www.contacal.com.br/contato/', :target => '_blank' %>!<br>-->
	Mudar para versão  
	<% if mobile_device? %>
	    <%= link_to "web", :mobile => 0 %>.
	  <% else %>
	    para <%= link_to "celular", :mobile => 1 %>.
	  <% end %>

	</p>
  </footer>
<script type="text/javascript"> 

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23488782-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript">
  $(document).ready(function(){
    $("a.terms-of-use-fancybox").fancybox({type: 'iframe', width: '60%', height: '75%'});
  });
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#primeira_vez").fancybox({type: 'iframe', width: '60%', height: '75%'}).trigger('click');
    });
</script> 

<script type="text/javascript">
    $(document).ready(function() {
       $('#close-button').click(function(){
          $.fancybox.close();
       })
    });
</script> 

<!-- Google Code for ContaCal Signup Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 961104544;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "Hh8_CMDp9wMQoJWlygM";
var google_conversion_value = 0;
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/961104544/?value=0&amp;label=Hh8_CMDp9wMQoJWlygM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


<!-- Google Code for Tag de remarketing -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 961104544;
var google_conversion_label = "rHi4CNC-9gQQoJWlygM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/961104544/?value=0&amp;label=rHi4CNC-9gQQoJWlygM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
$.src='//v2.zopim.com/?1faF4vVQbNmyw8avMgjitNMk5yeMshSm';z.t=+new Date;$.
type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
</script>
<!--End of Zopim Live Chat Script-->
<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6007333072121';
fb_param.value = '0.00';
fb_param.currency = 'BRL';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6007333072121&amp;value=0&amp;currency=BRL" /></noscript>



</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>ContaCal</title>
  <meta name="description" content="Sistema simples e eficiente para controlar suas calorias diárias. Basta vc registrar suas refeições e o sistema calcula automaticamente a quantidade de calorias ingerida e ainda informa se as calorias ingeridas são do tipo verde, amarela ou vermelha. As cores servem para indicar quão recomendável é ingerir o alimento. Se é um alimento de calorias vermelhas, é melhor evitá-lo ao máximo. Calorias amarelas podem ser ingeridas com moderação. Já as calorias verdes podem ser ingeridas sem restrição. Como sugestão, procure seguir a seguinte regra, não mais que 10% de calorias vermelhas, não mais que 35% de calorias amarelas e pelo menos 55% de calorias verdes.">
  <meta name="keywords" content="contador de calorias, conta calorias, calorias, emagrecer, emagrecimento, controle de calorias, controle de peso, perder peso, diário de calorias, perda de peso, alimentação saudável, nutrição, informação nutricional">
  <link href='/favicon.png' rel='shortcut icon'>
  <link href="/images/ContaCal-Icone-57x57.png" rel="apple-touch-icon" />
  <link href="/images/ContaCal-Icone-76x76.png" rel="apple-touch-icon" sizes="76x76" />
  <link href="/images/ContaCal-Icone-120x120.png" rel="apple-touch-icon" sizes="120x120" />
  <link href="/images/ContaCal-Icone-152x152.png" rel="apple-touch-icon" sizes="152x152" />
  <link href="/images/ContaCal-Icone-180x180.png" rel="apple-touch-icon" sizes="180x180" />
  <link href="/images/ContaCal-Icone-192x192.png" rel="icon" sizes="192x192" />
  <link href="/images/ContaCal-Icone-128x128.png" rel="icon" sizes="128x128" />
  <%= stylesheet_link_tag "contacal.mobile", "jquery-ui", "jquery.fancybox", "reset" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

<script type="text/javascript"> 
if(navigator.userAgent.match(/Android/i)){
   window.scrollTo(0,1);
}
</script>
  <!--[if lt IE 9]>
    <script src='http://html5shim.googlecode.com/svn/trunk/html5.js'></script>
  <![endif]-->

  <!--[if lte IE 7]>
    <link href="/stylesheets/iefix.css" media="all" rel="stylesheet" />
  <![endif]-->

</head>
<body id="<%= controller.controller_name %>">
  <header>
    <%- if user_signed_in? -%> 
    <%- if (current_user.status == 1 or current_user.status == 10) and user.expire_at.nil? -%>   
       <%- user.update_attribute(:expire_at, Date.today-1) -%>
    <%- end -%>
    <%- if (current_user.status == 1 or current_user.status == 10) and Date.today > user.expire_at -%>   
    <script language="JavaScript">
      self.location="/payment";
    </script>
    <%- end -%>
<!--      <div id="masthead">
        <p align=right>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
		<%- if current_user.kcal_limit.nil? or current_user.kcal_limit == 0 -%>
           <%= link_to "Definir limite diário", edit_user_registration_url %> &bull;
	    <%- end -%> 
	    <%- if user.status.blank? or user.status == 0 or user.status == 1 or user.status == 10 -%> 
	      <%= link_to "Assinar", payment_url %> 
        <%- elsif (user.status == 2 or user.status == 20) or (!user.expire_at.nil? and (user.status == 4 or user.status == 40))-%>
	      <%= link_to "Renovar assinatura", payment_url %>  
	    <%- else -%>
	      <%= link_to "Opções de assinatura", payment_url %>  
	    <%- end -%>
          &bull; <%= link_to "Alterar Dados", edit_user_registration_url %> &bull; <%= link_to "Ajuda", '/ajuda.html', :class => "terms-of-use-fancybox" %> &bull; <%= link_to "Blog", 'http://contacal.com.br/blog'%> &bull; <%= link_to "Site", 'http://contacal.com.br'%> &bull; <%= link_to "Sair", destroy_user_session_url, :method => :delete %>
      </div>-->
    <%- end -%>
    <div id="logo"><a href="<%= root_url(:protocol => "http") %>">ContaCal</a></div>
	<%- if (current_user.status == 0 or current_user.status == 1 or current_user.status == 10 or current_user.status == 2 or current_user.status == 4 or current_user.status == 20 or current_user.status == 40) and !user.expire_at.nil? and Date.today+10 > user.expire_at -%>
	<div id="subscriber">
		<%- if Date.today < user.expire_at -%>
          <br>Seu acesso<br>vence em <strong><%= user.expire_at.strftime("%d/%m/%Y") %></strong>.<br><a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- elsif Date.today == user.expire_at -%>
		  <br>Seu acesso<br>está expirando <strong>hoje</strong>!<br><a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- else -%>
	      <br>Seu acesso<br>expirou em <strong><%= user.expire_at.strftime("%d/%m/%Y") %></strong>.<br><a href=<%=payment_url%>><font color=#dd0000><b>Renove já</b></font></a>!
		<%- end -%>
    </div>
	<%- end -%>
    <%= yield(:header_info) %>

 


 </header>
  <hr />
  <%- if (current_user.status == 0 or current_user.status == 1 or current_user.status == 10 or current_user.status == 2 or current_user.status == 4 or current_user.status == 20 or current_user.status == 40)  and !user.expire_at.nil? and Date.today > user.expire_at -%>
<br />
<div class="alert" style="position: relative; margin-left: auto; margin-right: auto; margin-top: auto; width: 250px">
	<b>Seu acesso expirou... :-(</b><br /><br /><a href=<%=payment_url%>><font color=#dd0000><b>Renove já o seu acesso</b></font></a> para voltar a utilizar seu diário alimentar virtual e continuar a registrar suas refeições!<!--<br /><br />Quer usar mais alguns dias grátis? <a href="http://admin.contacal.com.br/user_friends/user_friend.cgi?from=<%=current_user.email%>" class="terms-of-use-fancybox"><font color=#dd0000><b>Indique</b></font></a> para seus amigos!-->
<br /><br />
</div>
  <%- else -%>
  <section role="main">
    <%= yield %>
  </section>
  <%- end -%>                  
  <hr />
  <footer>
<p align=center>
   <%= link_to "Renovar acesso", payment_url %> &bull; <%= link_to "Alterar Dados", edit_user_registration_url %> &bull; <%= link_to "Sair", destroy_user_session_url, :method => :delete,  :mobile => 1 %><br><br>


   <!--Copyright &copy; 2011 ContaCal.<br />-->Dúvidas? Sugestões? <%= mail_to "info@contacal.com.br", "Fale conosco", :subject => "[ContaCal] Contato via app!" %>!<br>
	Mudar para versão  
	<% if mobile_device? %>
	    <%= link_to "web", :mobile => 0 %>.
	  <% else %>
	    para <%= link_to "celular", :mobile => 1 %>.
	  <% end %>

	</p>
  </footer>
<script type="text/javascript"> 

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23488782-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type="text/javascript">
  $(document).ready(function(){
    $("a.terms-of-use-fancybox").fancybox({type: 'iframe', width: '70%', height: '100%'});
  });
</script>
<script type="text/javascript">
    $(document).ready(function() {
        $("#primeira_vez").fancybox({type: 'iframe', width: '70%', height: '100%'}).trigger('click');
    });
</script> 

<script type="text/javascript">
    $(document).ready(function() {
       $('#close-button').click(function(){
          $.fancybox.close();
       })
    });
</script> 

<!-- Google Code for Tag de remarketing -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 961104544;
var google_conversion_label = "rHi4CNC-9gQQoJWlygM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/961104544/?value=0&amp;label=rHi4CNC-9gQQoJWlygM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<script type="text/javascript">
var fb_param = {};
fb_param.pixel_id = '6007333072121';
fb_param.value = '0.00';
fb_param.currency = 'BRL';
(function(){
  var fpw = document.createElement('script');
  fpw.async = true;
  fpw.src = '//connect.facebook.net/en_US/fp.js';
  var ref = document.getElementsByTagName('script')[0];
  ref.parentNode.insertBefore(fpw, ref);
})();
</script>
<noscript><img height="1" width="1" alt="" style="display:none" src="https://www.facebook.com/offsite_event.php?id=6007333072121&amp;value=0&amp;currency=BRL" /></noscript>


</body>
</html>

app/views/layouts/devise.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>ContaCal</title>
  <meta name="description" content="Sistema simples e eficiente para controlar suas calorias diárias. Basta vc registrar suas refeições e o sistema calcula automaticamente a quantidade de calorias ingerida e ainda informa se as calorias ingeridas são do tipo verde, amarela ou vermelha. As cores servem para indicar quão recomendável é ingerir o alimento. Se é um alimento de calorias vermelhas, é melhor evitá-lo ao máximo. Calorias amarelas podem ser ingeridas com moderação. Já as calorias verdes podem ser ingeridas sem restrição. Como sugestão, procure seguir a seguinte regra, não mais que 10% de calorias vermelhas, não mais que 35% de calorias amarelas e pelo menos 55% de calorias verdes.">
  <meta name="keywords" content="contador de calorias, conta calorias, calorias, emagrecer, emagrecimento, controle de calorias, controle de peso, perder peso, diário de calorias, perda de peso, alimentação saudável, nutrição, informação nutricional">
  <link href='/favicon.png' rel='shortcut icon'>
  <link href="/images/ContaCal-Icone-57x57.png" rel="apple-touch-icon" />
  <link href="/images/ContaCal-Icone-76x76.png" rel="apple-touch-icon" sizes="76x76" />
  <link href="/images/ContaCal-Icone-120x120.png" rel="apple-touch-icon" sizes="120x120" />
  <link href="/images/ContaCal-Icone-152x152.png" rel="apple-touch-icon" sizes="152x152" />
  <link href="/images/ContaCal-Icone-180x180.png" rel="apple-touch-icon" sizes="180x180" />
  <link href="/images/ContaCal-Icone-192x192.png" rel="icon" sizes="192x192" />
  <link href="/images/ContaCal-Icone-128x128.png" rel="icon" sizes="128x128" />
  <%= stylesheet_link_tag "contacal.mobile", "jquery-ui", "jquery.fancybox", "reset", "iefix.mobile", "flash.mobile" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">

<script type="text/javascript"> 
if(navigator.userAgent.match(/Android/i)){
   window.scrollTo(0,1);
}
</script>
<!--  <link rel="stylesheet" href="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.css" />
  <link rel="stylesheet" href="/stylesheets/my.css" />
  <script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
  <script src="http://code.jquery.com/mobile/1.2.0/jquery.mobile-1.2.0.min.js"></script>
  <script src="/javascript/my.js"></script>-->

  <!--[if lt IE 9]>
    <script src='http://html5shim.googlecode.com/svn/trunk/html5.js'></script>
  <![endif]-->

  <!--[if lte IE 7]>
    <link href="/assets/iefix.css" media="all" rel="stylesheet" />
  <![endif]-->
</head>
	<%- if current_page?('/payment') or current_page?('/foods/new') or current_page?('/foods') -%>
<body id="dashboard">	                     
	<%- else -%>
<body id="users-engine" class="<%= controller.controller_name %>">
	<%- end -%>
  <header>
    <div id="logo">
      <a href="<%= root_url(:protocol => "http") %>">ContaCal</a>
    </div>
  </header>                    
  <hr />
  <section role="main">
    <%= yield %>
  </section>
  <hr />
  <footer>
    <p align=center><!--Copyright &copy; 2011 ContaCal.<br>-->Dúvidas? Sugestões? <%= mail_to "info@contacal.com.br", "Fale conosco", :subject => "[ContaCal] Contato via app!" %>!<br>
	Mudar para versão  
	<% if mobile_device? %>
	    <%= link_to "web", :mobile => 0 %>.
	  <% else %>
	    para <%= link_to "celular", :mobile => 1 %>.
	  <% end %>
	</p>
  </footer><br><br><br>
<script type="text/javascript"> 

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23488782-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- Google Code for Tag de remarketing -->
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
 
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 961104544;
var google_conversion_label = "rHi4CNC-9gQQoJWlygM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/961104544/?value=0&amp;label=rHi4CNC-9gQQoJWlygM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>


</body>
</html>